version: '3'

services:
  db_backoffice_professor:
    image: postgres
    restart: always
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      - POSTGRES_DB=backoffice_database
      - POSTGRES_USER=backoffice
      - POSTGRES_PASSWORD=backoffice123
    ports:
      - 5439:5432

  backend_backoffice:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - ALLOW_ORIGIN=http://localhost:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_backoffice_professor:5432/backoffice_database
      - SPRING_DATASOURCE_USERNAME=backoffice
      - SPRING_DATASOURCE_PASSWORD=backoffice123

networks:
  wordpress_net:
    driver: bridge