version: '3'

services:
  db_backoffice_professor:
    image: mongo
    restart: always
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_DATABASE=backoffice_database
      - MONGO_INITDB_ROOT_USERNAME=backoffice
      - MONGO_INITDB_ROOT_PASSWORD=backoffice123
    ports:
      - 27017:27017

  backend_backoffce:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - ALLOW_ORIGIN=http://localhost:8080
      - SPRING_DATA_MONGODB_HOST=db_backoffice_professor
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=backoffice_database
      - SPRING_DATA_MONGODB_USERNAME=backoffice
      - SPRING_DATA_MONGODB_PASSWORD=backoffice123

networks:
  wordpress_net:
    driver: bridge
