spring:
  data:
    mongodb:
      host: db_backoffice_professor
      port: 27017
      database: backoffice_database
      username: backoffice
      password: backoffice123
      uri: mongodb://backoffice:backoffice123@db_backoffice_professor:27017/backoffice_database


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

