spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/backoffice_database
    username: backoffice
    password: backoffice123
    driver-class-name: org.postgresql.Driver
    ddl-auto: update
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 30000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
